name: Deploy

on:
  workflow_call:
    inputs:
      framework: 
        description: '.net framework'
        type: string
        required: true
        default: net6.0
      branch:
        description: 'Git branch used for this build'
        type: string
        required: true
        default: main
      major_version:
        description: 'Sonarr major version'
        type: string
        required: true
        default: 4
      version:
        description: 'Sonarr version'
        type: string
        required: true
        default: 4.0.0.0

jobs:
  package:
    strategy:
      matrix:
        platform: [linux]
        include:
          - platform: linux
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Package
      uses: ./.github/actions/package-edited
      with:
        framework: ${{ inputs.framework }}
        platform: ${{ matrix.platform }}
        artifact: build_${{ matrix.platform }}
        branch: ${{ inputs.branch }}
        major_version: ${{ inputs.major_version }}
        version: ${{ inputs.version }}

  release:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Download release artifacts
      uses: actions/download-artifact@v4
      with:
        path: _artifacts
        pattern: release_*
        merge-multiple: true

    - name: Generate Release Notes
      id: generate-release-notes
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        result-encoding: string
        script: |
          const { data } = await github.rest.repos.generateReleaseNotes({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: 'v${{ inputs.version }}',
            target_commitish: '${{ github.sha }}',
          })
          return data.body
   
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: _artifacts/Sonarr.*
        commit: ${{ github.sha }}
        generateReleaseNotes: false
        body: ${{ steps.generate-release-notes.outputs.result }}
        name: ${{ inputs.version }}
        tag: v${{ inputs.version }}
  
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

  docker-trigger:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: docker trigger event
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" -d '{"ref":"master", "inputs":{"version": "${{ inputs.version }}","framework": "${{ inputs.framework }}"}}' https://api.github.com/repos/myhme/docker-sonarr/actions/workflows/external_trigger_edited.yml/dispatches